apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-airflow
  labels:
    app: {{ .Release.Name }}-airflow
  annotations:
{{ toYaml .Values.airflow.service.annotations | indent 4 }}
spec:
  type: {{ .Values.airflow.service.type }}
  ports:
    - name: web
      port: {{ .Values.airflow.service.port }}
      targetPort: {{ .Values.airflow.service.targetPort | default .Values.airflow.service.port }}
  selector:
    app: {{ .Release.Name }}-airflow