apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gbr.fullname" . }}-postgres-secret
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.postgres.db | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gbr.fullname" . }}-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "gbr.fullname" . }}-postgres
  template:
    metadata:
      labels:
        app: {{ include "gbr.fullname" . }}-postgres
    spec:
      containers:
        - name: postgresql
          image: "{{ .Values.image.postgres.repository }}:{{ .Values.image.postgres.tag }}"
          imagePullPolicy: {{ .Values.image.postgres.pullPolicy }}
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: {{ include "gbr.fullname" . }}-postgres-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "gbr.fullname" . }}-postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "gbr.fullname" . }}-postgres-secret
                  key: POSTGRES_PASSWORD
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-data
{{- if .Values.pvc.enabled }}
          persistentVolumeClaim:
            claimName: ml-data-pvc
{{- else }}
          emptyDir: {}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "gbr.fullname" . }}-postgres
spec:
  selector:
    app: {{ include "gbr.fullname" . }}-postgres
  ports:
    - port: 5432
      targetPort: 5432