name: gradient-boosted-regression
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas
  - numpy
  - scikit-learn
  - seaborn
  - pip
  - pip:
    - mlflow
    - kaggle
    - pytest
    - awscli
    - boto3
    - sagemaker