FROM python:3.10-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install -r requirements.txt
COPY serving/ ./serving/
COPY utils/ ./utils/
ENV PYTHONPATH=/app
EXPOSE 8080
CMD ["python", "-m", "serving.serve"]
