# k8s/mlflow.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow-server
  template:
    metadata:
      labels:
        app: mlflow-server
    spec:
      containers:
      - name: mlflow
        image: gbr-mlflow:latest  # Use custom image
        imagePullPolicy: Never    # Use local image
        command: ["mlflow", "server"]
        args:
        - "--host=0.0.0.0"
        - "--port=5000"
        - "--backend-store-uri=sqlite:////app/shared/mlflow.db"
        - "--default-artifact-root=/app/shared/artifacts"
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: shared-data
          mountPath: /app/shared
        workingDir: /app
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: ml-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-service
spec:
  selector:
    app: mlflow-server
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP